/** Generated from contract/openapi/workspace-v1.yaml; do not edit by hand. */
export const PROTOCOL = "workspace.v1" as const;
export type HeadersLike = Record<string, string>;
export type Transport = (method: string, path: string, headers: HeadersLike, body?: Uint8Array) => Promise<{ status: number; headers: HeadersLike; body: Uint8Array }>;
export interface Health { status: "ok" | "degraded"; protocol: typeof PROTOCOL; schema_digest: string; runtime_epoch: number }
export interface Handshake { protocol: typeof PROTOCOL; schema_digest: string; session_id: string; actor_id: string; realm_id: string; scopes: string[] }
export interface Realm { realm_id: string; display_name: string; version: number; created_at: string; state?: "active" | "tombstoned"; tombstoned_at?: string | null; lifecycle_version?: number }
export interface IntegrityCheck { ok: boolean; [key: string]: unknown }
export interface IntegrityReport { state: "ready" | "unhealthy"; ok: boolean; schema_version: number; recovery_action: string; issues?: string[]; checks: Record<string, IntegrityCheck> }
export interface RealmLifecycle { realm_id: string; state: "active" | "tombstoned"; version: number; tombstoned_at?: string | null; reason?: string | null }
export interface Project { project_id: string; realm_id: string; slug: string; name: string; metadata: Record<string, unknown>; version: number; created_at: string; updated_at: string; archived?: boolean }
export interface ProjectDocument { document_id: string; project_id: string; kind: string; content: unknown; version: number; created_at: string; updated_at: string }
export interface Generation { generation_id: string; project_id: string; source_task_id?: string | null; type: string; status: string; metadata: Record<string, unknown>; version: number; created_at: string; updated_at: string }
export interface GenerationVariant { variant_id: string; generation_id: string; object_id?: string | null; variant_type: string; metadata: Record<string, unknown>; created_at: string }
export interface ManagedObject { object_id: string; digest: string; media_type: string; size: number; version: number; created_at: string; filename?: string; relation?: string }
export interface MediaRelation { project_id: string; from_object_id: string; to_object_id: string; kind: "derived_from" | "variant_of" | "uses_as_input" | "mask_for" | "audio_for"; metadata: Record<string, unknown>; created_at: string }
export interface ByteResponse { data: Uint8Array; status: number; headers: HeadersLike; etag?: string; content_range?: string }
export type TaskState = "queued" | "ready" | "running" | "succeeded" | "failed" | "cancel_requested" | "cancelled" | "retrying";
export interface Task { task_id: string; run_id: string; state: TaskState; version: number; capability_id: string; capability_digest: string; idempotency_key: string; created_at: string; updated_at: string; attempt_id?: string | null; runtime_epoch: number; spec: Record<string, unknown>; result?: Record<string, unknown> | null }
export interface AttemptFence { attempt_id: string; task_id: string; lease_id: string; fence: number; lease_expires_at: string; runtime_epoch: number; spec: Record<string, unknown> }
export interface ClaimWaiting { task: Task; waiting_reason: "waiting_for_worker" | "capability_unavailable" | "insufficient_storage" | "waiting_for_gpu" | "waiting_for_cpu" | "waiting_for_network" }
export interface RecoveryAuthorization { attempt_id: string; task_id: string; executor_id: string; runtime_epoch: number; nonce: string; expires_in_seconds: number }
export interface RecoveryCheckpointReceipt { checkpoint_id: string; attempt_id: string; task_id: string; runtime_epoch: number; nonce: string; digest: string; size: number; state: string; path?: string }
export interface RecoveryReceipt { type: string; checkpoint_id: string; attempt_id: string; task_id: string; runtime_epoch: number; command: string; status: string; version?: number; checkpoint_digest?: string; executor_result?: unknown; checkpoint?: unknown; error?: { type: string; message: string } }
export interface RecoveryResumeReceipt { receipt: RecoveryReceipt; attempt: AttemptFence }
export interface Event { event_id: string; sequence: number; cursor: string; event_type: string; aggregate_type: string; aggregate_id: string; payload: Record<string, unknown>; occurred_at: string }
export type CapabilityStatus = "ready" | "unavailable" | "unsupported" | "retired";
export interface Capability { capability_id: string; definition_digest: string; status: CapabilityStatus; required_resource_keys: string[]; estimated_scratch_bytes: number; estimated_output_bytes: number; unavailable_reason?: string | null }
export interface Executor { executor_id: string; max_concurrency: number; resource_keys: string[]; capabilities: Capability[]; protocol: typeof PROTOCOL; runtime_epoch?: number }
export class ApiError extends Error { constructor(public status: number, public code: string, message: string, public request_id = "", public details: Record<string, unknown> = {}) { super(`${code}: ${message}`); this.name = "ApiError" } }

export class WorkspaceClient {
  public handshakeInfo?: Handshake;
  constructor(private readonly baseUrl: string, private readonly token?: string, private readonly transport?: Transport) {}
  private async request(method: string, path: string, body?: Uint8Array, headers: HeadersLike = {}, expected = [200]): Promise<{ status: number; headers: HeadersLike; body: Uint8Array }> {
    const requestHeaders: HeadersLike = { Accept: "application/json", ...headers };
    if (this.token) requestHeaders.Authorization ??= `Bearer ${this.token}`;
    let response: { status: number; headers: HeadersLike; body: Uint8Array };
    if (this.transport) response = await this.transport(method, path, requestHeaders, body);
    else {
      const responseObj = await fetch(`${this.baseUrl.replace(/\/$/, "")}${path}`, { method, headers: requestHeaders, body: body as BodyInit | undefined });
      const bytes = new Uint8Array(await responseObj.arrayBuffer());
      const responseHeaders: HeadersLike = {}; responseObj.headers.forEach((value, key) => { responseHeaders[key] = value });
      response = { status: responseObj.status, headers: responseHeaders, body: bytes };
    }
    if (!expected.includes(response.status)) throw this.decodeError(response.status, response.body);
    return response;
  }
  private decodeError(status: number, body: Uint8Array): ApiError { try { const v = JSON.parse(new TextDecoder().decode(body)); return new ApiError(status, v.code ?? "http_error", v.message ?? `HTTP ${status}`, v.request_id ?? "", v.details ?? {}) } catch { return new ApiError(status, "http_error", `HTTP ${status}`) } }
  private json<T>(body: Uint8Array): T { return JSON.parse(new TextDecoder().decode(body)) as T }
  async health(): Promise<Health> { return this.json<Health>((await this.request("GET", "/v1/health")).body) }
  async handshake(client_name: string, client_version: string, requested_scopes: string[]): Promise<Handshake> { const v = this.json<Handshake>((await this.request("POST", "/v1/handshake", new TextEncoder().encode(JSON.stringify({ protocol: PROTOCOL, client_name, client_version, requested_scopes })), { "Content-Type": "application/json" })).body); this.handshakeInfo = v; return v }
  async getRealm(): Promise<Realm> { return this.json<Realm>((await this.request("GET", "/v1/realm")).body) }
  async doctor(): Promise<IntegrityReport> { return this.json<IntegrityReport>((await this.request("GET", "/v1/doctor")).body) }
  async createBackup(destination: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", "/v1/backup", new TextEncoder().encode(JSON.stringify({ destination })), { "Content-Type": "application/json" }, [200, 201])).body) }
  async restoreBackup(backup: string, destination: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", "/v1/restore", new TextEncoder().encode(JSON.stringify({ backup, destination })), { "Content-Type": "application/json" }, [200, 201])).body) }
  async exportRealm(): Promise<Record<string, unknown>> { return this.json((await this.request("GET", "/v1/export")).body) }
  async tombstoneRealm(reason?: string, expectedVersion?: number): Promise<RealmLifecycle> { const payload: Record<string, unknown> = {}; if (reason !== undefined) payload.reason = reason; if (expectedVersion !== undefined) payload.expected_version = expectedVersion; return this.json<RealmLifecycle>((await this.request("POST", "/v1/realm/tombstone", new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json" })).body) }
  async recoverRealm(expectedVersion?: number): Promise<RealmLifecycle> { const payload = expectedVersion === undefined ? {} : { expected_version: expectedVersion }; return this.json<RealmLifecycle>((await this.request("POST", "/v1/realm/recover", new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json" })).body) }
  async purgeRealm(confirmation: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", "/v1/realm/purge", new TextEncoder().encode(JSON.stringify({ confirmation })), { "Content-Type": "application/json" })).body) }
  async createProject(name: string, idempotencyKey: string, slug?: string, metadata?: Record<string, unknown>): Promise<Project> { const payload: Record<string, unknown> = { name }; if (slug !== undefined) payload.slug = slug; if (metadata !== undefined) payload.metadata = metadata; return this.json<Project>((await this.request("POST", "/v1/projects", new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async getProject(projectId: string): Promise<Project> { return this.json<Project>((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}`)).body) }
  async updateProject(projectId: string, expectedVersion?: number, name?: string, metadata?: Record<string, unknown>): Promise<Project> { const payload: Record<string, unknown> = {}; if (expectedVersion !== undefined) payload.expected_version = expectedVersion; if (name !== undefined) payload.name = name; if (metadata !== undefined) payload.metadata = metadata; return this.json<Project>((await this.request("PATCH", `/v1/projects/${encodeURIComponent(projectId)}`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json" })).body) }
  async createDocument(projectId: string, documentId: string, kind: string, content: unknown): Promise<ProjectDocument> { return this.json<ProjectDocument>((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/documents`, new TextEncoder().encode(JSON.stringify({ document_id: documentId, kind, content })), { "Content-Type": "application/json" }, [200, 201])).body) }
  async listDocuments(projectId: string): Promise<{ items: ProjectDocument[]; next_cursor: string | null }> { return this.json((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/documents`)).body) }
  async getDocument(projectId: string, documentId: string): Promise<ProjectDocument> { return this.json<ProjectDocument>((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}`)).body) }
  async updateDocument(projectId: string, documentId: string, expectedVersion: number, content?: unknown, kind?: string): Promise<ProjectDocument> { const payload: Record<string, unknown> = { expected_version: expectedVersion }; if (content !== undefined) payload.content = content; if (kind !== undefined) payload.kind = kind; return this.json<ProjectDocument>((await this.request("PATCH", `/v1/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(documentId)}`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json" })).body) }
  async listProjects(cursor?: string, limit = 50): Promise<{ items: Project[]; next_cursor: string | null }> { return this.json((await this.request("GET", `/v1/projects?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async createTimeline(projectId: string, timelineId: string, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/timelines`, new TextEncoder().encode(JSON.stringify({ timeline_id: timelineId })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async createTimelineDocument(projectId: string, timelineId: string, config: Record<string, unknown>, registry: Record<string, unknown>, idempotencyKey: string, slug?: string | null, name?: string | null): Promise<Record<string, unknown>> {
    slug ??= timelineId; name ??= slug;
    const timeline = await this.createTimeline(projectId, timelineId, idempotencyKey);
    const content = { slug, name, config, registry };
    let document: ProjectDocument | undefined;
    let lastError: unknown;
    for (let attempt = 0; attempt < 2; attempt += 1) {
      try { document = await this.createDocument(projectId, `timeline:${timelineId}`, "timeline.composition", content); break; }
      catch (error) { lastError = error; }
    }
    if (!document) throw lastError ?? new Error("timeline composition document was not persisted; retry the same idempotency key");
    return { ...timeline, slug, name, config_version: document.version, config, registry };
  }
  async updateTimelineDocument(projectId: string, timelineId: string, expectedVersion: number, config: Record<string, unknown>, registry: Record<string, unknown>, slug?: string, name?: string): Promise<Record<string, unknown>> {
    const current = await this.getDocument(projectId, `timeline:${timelineId}`);
    const content: Record<string, unknown> = { ...(current.content as Record<string, unknown>), config, registry };
    if (slug !== undefined) content.slug = slug;
    if (name !== undefined) content.name = name;
    const document = await this.updateDocument(projectId, `timeline:${timelineId}`, expectedVersion, content);
    const timeline = await this.getTimeline(timelineId);
    return { ...timeline, slug: content.slug ?? timelineId, name: content.name ?? timelineId, config_version: document.version, config, registry };
  }
  async listTimelines(projectId: string, cursor?: string, limit = 50): Promise<{ items: Record<string, unknown>[]; next_cursor: string | null }> { return this.json((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/timelines?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async getTimeline(timelineId: string): Promise<Record<string, unknown>> { return this.json((await this.request("GET", `/v1/timelines/${encodeURIComponent(timelineId)}`)).body) }
  async listTimelineHistory(timelineId: string, cursor?: string, limit = 50): Promise<{ items: Record<string, unknown>[]; next_cursor: string | null }> { return this.json((await this.request("GET", `/v1/timelines/${encodeURIComponent(timelineId)}/history?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async diffTimeline(timelineId: string, fromVersion: number, toVersion: number): Promise<Record<string, unknown>> { return this.json((await this.request("GET", `/v1/timelines/${encodeURIComponent(timelineId)}/diff?from_version=${fromVersion}&to_version=${toVersion}`)).body) }
  async archiveTimeline(timelineId: string, expectedVersion: number, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/timelines/${encodeURIComponent(timelineId)}/archive`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async recoverTimeline(timelineId: string, expectedVersion: number, version: number, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/timelines/${encodeURIComponent(timelineId)}/recover`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion, version })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async updateTimeline(timelineId: string, expectedVersion: number, shots?: Record<string, unknown>[], references?: Record<string, unknown>[]): Promise<Record<string, unknown>> { const payload: Record<string, unknown> = { expected_version: expectedVersion }; if (shots !== undefined) payload.shots = shots; if (references !== undefined) payload.references = references; return this.json((await this.request("PATCH", `/v1/timelines/${encodeURIComponent(timelineId)}`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json" })).body) }
  async createShot(timelineId: string, shot: Record<string, unknown>, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/timelines/${encodeURIComponent(timelineId)}/shots`, new TextEncoder().encode(JSON.stringify(shot)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async getShot(shotId: string): Promise<Record<string, unknown>> { return this.json((await this.request("GET", `/v1/shots/${encodeURIComponent(shotId)}`)).body) }
  async listProjectShots(projectId: string, cursor?: string, limit = 50, includeArchived = false): Promise<{ items: Record<string, unknown>[]; next_cursor: string | null }> { return this.json((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/shots?limit=${limit}&include_archived=${includeArchived}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async updateShot(shotId: string, expectedVersion: number, startMs?: number, durationMs?: number, referenceIds?: string[]): Promise<Record<string, unknown>> { const payload: Record<string, unknown> = { expected_version: expectedVersion }; if (startMs !== undefined) payload.start_ms = startMs; if (durationMs !== undefined) payload.duration_ms = durationMs; if (referenceIds !== undefined) payload.reference_ids = referenceIds; return this.json((await this.request("PATCH", `/v1/shots/${encodeURIComponent(shotId)}`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json" })).body) }
  async archiveShot(shotId: string, expectedVersion: number, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/shots/${encodeURIComponent(shotId)}/archive`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async recoverShot(shotId: string, expectedVersion: number, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/shots/${encodeURIComponent(shotId)}/recover`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async createReference(timelineId: string, reference: Record<string, unknown>, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/timelines/${encodeURIComponent(timelineId)}/references`, new TextEncoder().encode(JSON.stringify(reference)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async getReference(referenceId: string): Promise<Record<string, unknown>> { return this.json((await this.request("GET", `/v1/references/${encodeURIComponent(referenceId)}`)).body) }
  async listProjectReferences(projectId: string, cursor?: string, limit = 50, includeArchived = false): Promise<{ items: Record<string, unknown>[]; next_cursor: string | null }> { return this.json((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/references?limit=${limit}&include_archived=${includeArchived}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async updateReference(referenceId: string, expectedVersion: number, objectId?: string, role?: string): Promise<Record<string, unknown>> { const payload: Record<string, unknown> = { expected_version: expectedVersion }; if (objectId !== undefined) payload.object_id = objectId; if (role !== undefined) payload.role = role; return this.json((await this.request("PATCH", `/v1/references/${encodeURIComponent(referenceId)}`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json" })).body) }
  async archiveReference(referenceId: string, expectedVersion: number, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/references/${encodeURIComponent(referenceId)}/archive`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async recoverReference(referenceId: string, expectedVersion: number, idempotencyKey: string): Promise<Record<string, unknown>> { return this.json((await this.request("POST", `/v1/references/${encodeURIComponent(referenceId)}/recover`, new TextEncoder().encode(JSON.stringify({ expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async ingestObject(data: Uint8Array, mediaType: string, idempotencyKey: string, filename?: string): Promise<ManagedObject> { const headers: HeadersLike = { "Content-Type": mediaType, "Idempotency-Key": idempotencyKey }; if (filename) headers["X-Filename"] = filename; return this.json<ManagedObject>((await this.request("POST", "/v1/objects", data, headers, [200, 201])).body) }
  async ingestProjectObject(projectId: string, data: Uint8Array, mediaType: string, idempotencyKey: string, filename?: string): Promise<ManagedObject> { const headers: HeadersLike = { "Content-Type": mediaType, "Idempotency-Key": idempotencyKey }; if (filename) headers["X-Original-Name"] = filename; return this.json<ManagedObject>((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/objects`, data, headers, [200, 201])).body) }
  async listProjectObjects(projectId: string, cursor?: string, limit = 50): Promise<{ items: ManagedObject[]; next_cursor: string | null }> { return this.json((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/objects?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async listObjects(projectId: string, cursor?: string, limit = 50): Promise<{ items: ManagedObject[]; next_cursor: string | null }> { return this.listProjectObjects(projectId, cursor, limit) }
  async listProjectMedia(projectId: string, cursor?: string, limit = 50): Promise<{ items: ManagedObject[]; next_cursor: string | null }> { return this.listProjectObjects(projectId, cursor, limit) }
  async listMedia(projectId: string, cursor?: string, limit = 50): Promise<{ items: ManagedObject[]; next_cursor: string | null }> { return this.listProjectObjects(projectId, cursor, limit) }
  async createMediaRelation(projectId: string, fromObjectId: string, toObjectId: string, kind: MediaRelation["kind"], idempotencyKey: string, metadata: Record<string, unknown> = {}): Promise<MediaRelation> { return this.json<MediaRelation>((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/media-relations`, new TextEncoder().encode(JSON.stringify({ from_object_id: fromObjectId, to_object_id: toObjectId, kind, metadata })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async listMediaRelations(projectId: string, cursor?: string, limit = 50): Promise<{ items: MediaRelation[]; next_cursor: string | null }> { return this.json((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/media-relations?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async getObject(objectId: string, byteRange?: [number, number?]): Promise<ByteResponse> { const headers: HeadersLike = {}; if (byteRange) { if (byteRange[0] < 0 || (byteRange[1] !== undefined && byteRange[1] < byteRange[0])) throw new Error("invalid byte range"); headers.Range = `bytes=${byteRange[0]}-${byteRange[1] ?? ""}` } const r = await this.request("GET", `/v1/objects/${encodeURIComponent(objectId)}`, undefined, headers, [200, 206]); return { data: r.body, status: r.status, headers: r.headers, etag: r.headers.ETag ?? r.headers.etag, content_range: r.headers["Content-Range"] ?? r.headers["content-range"] } }
  async headObject(objectId: string, byteRange?: [number, number?]): Promise<ByteResponse> { const headers: HeadersLike = {}; if (byteRange) headers.Range = `bytes=${byteRange[0]}-${byteRange[1] ?? ""}`; const r = await this.request("HEAD", `/v1/objects/${encodeURIComponent(objectId)}`, undefined, headers, [200, 206]); return { data: r.body, status: r.status, headers: r.headers, etag: r.headers.ETag ?? r.headers.etag, content_range: r.headers["Content-Range"] ?? r.headers["content-range"] } }
  async admitTask(input: { capability_id: string; capability_digest: string; input_object_ids: string[]; schema_version?: string; settlement_effect?: Record<string, unknown>; project?: string; spec?: Record<string, unknown> }, idempotencyKey: string): Promise<Task> { return this.json<Task>((await this.request("POST", "/v1/tasks", new TextEncoder().encode(JSON.stringify({ schema_version: "1", ...input })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async getTask(taskId: string): Promise<Task> { return this.json<Task>((await this.request("GET", `/v1/tasks/${encodeURIComponent(taskId)}`)).body) }
  async listProjectTasks(projectId: string, cursor?: string, limit = 50): Promise<{ items: Task[]; next_cursor: string | null }> { return this.json((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/tasks?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async listTasks(projectId: string, cursor?: string, limit = 50): Promise<{ items: Task[]; next_cursor: string | null }> { return this.listProjectTasks(projectId, cursor, limit) }
  async claimTask(executorId: string, capabilityIds: string[], idempotencyKey: string, runtimeEpoch: number): Promise<AttemptFence | ClaimWaiting | undefined> { const payload = { executor_id: executorId, capability_ids: capabilityIds, runtime_epoch: runtimeEpoch }; const r = await this.request("POST", "/v1/tasks/claim", new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 204]); if (r.status === 204) return undefined; const value = this.json<AttemptFence | ClaimWaiting>(r.body); return "waiting_reason" in value ? value as ClaimWaiting : value as AttemptFence }
  async cancelTask(taskId: string, idempotencyKey: string, expectedVersion?: number): Promise<Task> { return this.transitionTask(taskId, "cancel", idempotencyKey, expectedVersion) }
  async retryTask(taskId: string, idempotencyKey: string, expectedVersion?: number): Promise<Task> { return this.transitionTask(taskId, "retry", idempotencyKey, expectedVersion) }
  private async transitionTask(taskId: string, action: "cancel" | "retry", idempotencyKey: string, expectedVersion?: number): Promise<Task> { return this.json<Task>((await this.request("POST", `/v1/tasks/${encodeURIComponent(taskId)}/${action}`, new TextEncoder().encode(JSON.stringify(expectedVersion === undefined ? {} : { expected_version: expectedVersion })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async getRun(runId: string): Promise<Record<string, unknown>> { return this.json((await this.request("GET", `/v1/runs/${encodeURIComponent(runId)}`)).body) }
  async listProjectRuns(projectId: string, cursor?: string, limit = 50): Promise<{ items: Record<string, unknown>[]; next_cursor: string | null }> { return this.json((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/runs?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)).body) }
  async listRuns(projectId: string, cursor?: string, limit = 50): Promise<{ items: Record<string, unknown>[]; next_cursor: string | null }> { return this.listProjectRuns(projectId, cursor, limit) }
  async listRunEvents(runId: string): Promise<Event[]> { const value = this.json<unknown>((await this.request("GET", `/v1/runs/${encodeURIComponent(runId)}/events`)).body); return (Array.isArray(value) ? value : (value as { items: Event[] }).items).map((item) => item as Event) }
  async listEvents(cursor?: string, limit = 50, aggregateId?: string): Promise<{ items: Event[]; next_cursor: string | null }> { const query = `/v1/events?limit=${limit}${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}${aggregateId ? `&aggregate_id=${encodeURIComponent(aggregateId)}` : ""}`; return this.json((await this.request("GET", query)).body) }
  async registerExecutor(executor: Executor, idempotencyKey: string): Promise<Executor> { return this.json<Executor>((await this.request("POST", "/v1/executors", new TextEncoder().encode(JSON.stringify(executor)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, [200, 201])).body) }
  async listCapabilities(): Promise<Capability[]> { return this.json<{ items: Capability[] }>((await this.request("GET", "/v1/capabilities")).body).items }
  async registerCapability(capability: Omit<Capability, "status" | "required_resource_keys" | "estimated_scratch_bytes" | "estimated_output_bytes"> & Partial<Pick<Capability, "status" | "required_resource_keys" | "estimated_scratch_bytes" | "estimated_output_bytes">>, idempotencyKey?: string): Promise<Capability> { const headers: HeadersLike = { "Content-Type": "application/json" }; if (idempotencyKey) headers["Idempotency-Key"] = idempotencyKey; return this.json<Capability>((await this.request("POST", "/v1/capabilities", new TextEncoder().encode(JSON.stringify({ status: "ready", required_resource_keys: [], estimated_scratch_bytes: 0, estimated_output_bytes: 0, ...capability })), headers, [200, 201])).body) }
  async settleAttempt(attemptId: string, settlement: Record<string, unknown>, idempotencyKey: string): Promise<Task> { return this.json<Task>((await this.request("POST", `/v1/attempts/${encodeURIComponent(attemptId)}/settle`, new TextEncoder().encode(JSON.stringify(settlement)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async failAttempt(attemptId: string, leaseId: string, fence: number, error: unknown, runtimeEpoch: number, idempotencyKey: string): Promise<Task> { return this.json<Task>((await this.request("POST", `/v1/attempts/${encodeURIComponent(attemptId)}/fail`, new TextEncoder().encode(JSON.stringify({ lease_id: leaseId, fence, runtime_epoch: runtimeEpoch, error })), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async heartbeatAttempt(attemptId: string, leaseId: string, fence: number, idempotencyKey: string, runtimeEpoch: number): Promise<AttemptFence> { const payload = { lease_id: leaseId, fence, runtime_epoch: runtimeEpoch }; return this.json<AttemptFence>((await this.request("POST", `/v1/attempts/${encodeURIComponent(attemptId)}/heartbeat`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json", "Idempotency-Key": idempotencyKey })).body) }
  async prepareReboot(attemptId: string, leaseId: string, fence: number, runtimeEpoch: number): Promise<RecoveryAuthorization> { const payload = { lease_id: leaseId, fence, runtime_epoch: runtimeEpoch }; return this.json<RecoveryAuthorization>((await this.request("POST", `/v1/attempts/${encodeURIComponent(attemptId)}/prepare-reboot`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json" })).body) }
  async checkpointAttempt(attemptId: string, leaseId: string, fence: number, nonce: string, authorization: string, runtimeEpoch: number, state: Record<string, unknown> = {}): Promise<RecoveryCheckpointReceipt> { const payload = { lease_id: leaseId, fence, nonce, authorization, state, runtime_epoch: runtimeEpoch }; return this.json<RecoveryCheckpointReceipt>((await this.request("POST", `/v1/attempts/${encodeURIComponent(attemptId)}/checkpoint`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json" }, [200, 201])).body) }
  async requestReboot(checkpointId: string, nonce: string, authorization: string, runtimeEpoch: number, command = "reboot"): Promise<RecoveryReceipt> { return this.json<RecoveryReceipt>((await this.request("POST", "/v1/recovery/reboot", new TextEncoder().encode(JSON.stringify({ checkpoint_id: checkpointId, nonce, authorization, runtime_epoch: runtimeEpoch, command })), { "Content-Type": "application/json" })).body) }
  async resumeAttempt(checkpointId: string, nonce: string, authorization: string, runtimeEpoch: number): Promise<RecoveryResumeReceipt> { return this.json<RecoveryResumeReceipt>((await this.request("POST", "/v1/recovery/resume", new TextEncoder().encode(JSON.stringify({ checkpoint_id: checkpointId, nonce, authorization, runtime_epoch: runtimeEpoch })), { "Content-Type": "application/json" })).body) }
  async listGenerations(projectId: string): Promise<{ items: Generation[]; next_cursor: string | null }> { return this.json((await this.request("GET", `/v1/projects/${encodeURIComponent(projectId)}/generations`)).body) }
  async createGeneration(projectId: string, generationId: string, metadata: Record<string, unknown> = {}, type = "generation", sourceTaskId?: string): Promise<Generation> { const payload: Record<string, unknown> = { generation_id: generationId, metadata, type }; if (sourceTaskId !== undefined) payload.source_task_id = sourceTaskId; return this.json<Generation>((await this.request("POST", `/v1/projects/${encodeURIComponent(projectId)}/generations`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json" }, [200, 201])).body) }
  async getGeneration(generationId: string): Promise<Generation> { return this.json<Generation>((await this.request("GET", `/v1/generations/${encodeURIComponent(generationId)}`)).body) }
  async listVariants(generationId: string): Promise<{ items: GenerationVariant[]; next_cursor: string | null }> { return this.json((await this.request("GET", `/v1/generations/${encodeURIComponent(generationId)}/variants`)).body) }
  async getVariant(variantId: string): Promise<GenerationVariant> { return this.json<GenerationVariant>((await this.request("GET", `/v1/variants/${encodeURIComponent(variantId)}`)).body) }
  async createVariant(generationId: string, variantId: string, objectId?: string, variantType = "original", metadata: Record<string, unknown> = {}): Promise<GenerationVariant> { const payload: Record<string, unknown> = { variant_id: variantId, variant_type: variantType, metadata }; if (objectId !== undefined) payload.object_id = objectId; return this.json<GenerationVariant>((await this.request("POST", `/v1/generations/${encodeURIComponent(generationId)}/variants`, new TextEncoder().encode(JSON.stringify(payload)), { "Content-Type": "application/json" }, [200, 201])).body) }
}
